"""
Independent External AI Verifier for TrustGuard AI.
Evaluates answers generated by external AI models (ChatGPT, Gemini, Claude, Perplexity, etc.)
or extracted from user screens across 7 verification modes with calibrated trust scoring.
"""

import re
import uuid
import time
import logging
from typing import List, Dict, Any, Optional, Tuple

from app.schemas import (
    AnalyzeRequest,
    AnalyzeResponse,
    AnalyzeScreenRequest,
    AnalyzeMode,
    ClaimAnalysisItem,
    ClaimStatus,
    AskAndVerifyRequest,
    AskAndVerifyResponse,
)
from app.agent.tools import tools
from app.agent.verifier_cache import verifier_cache
from app.token_saver.engine import token_saver_engine, estimate_tokens
from app.agent.risk import risk_classifier
from app.llm import llm_client

logger = logging.getLogger("trustguard.verifier")

# Known common hallucination & adversarial trap patterns
KNOWN_TRAP_PATTERNS = [
    (r"(?i)\b2031\s+chess\s+olympiad\b", "The 2031 Chess Olympiad has not occurred and has no recorded winner."),
    (r"(?i)\batlantis\b.*\b(population|capital|census)\b", "Atlantis is a mythological allegory from Plato, not a physical modern city with census data."),
    (r"(?i)\bphlogiston\b.*\b(combustion|element)\b", "Phlogiston theory was obsolete scientific hypothesis superseded by oxygen chemistry in the 1770s."),
    (r"(?i)\bchronosync\s+protocol\b", "Chronosync is a fictitious protocol with no IETF standard."),
    (r"(?i)\bquantum\s+telekinesis\b", "Quantum telekinesis is not scientifically established."),
    (r"(?i)\bcure\s+for\s+cancer\s+by\s+drinking\s+bleach\b", "Consuming bleach is lethal and hazardous."),
]

# Patterns that indicate the prompt/query is requesting misinformation, fabrication, or deliberate falsehoods.
# Format: (compiled_pattern, reason_string)
MISINFORMATION_INTENT_PATTERNS: List[Tuple[re.Pattern, str]] = [
    # Explicit requests for lies or fake content
    (re.compile(r"(?i)\b(tell\s+(me\s+)?a?\s*lie|say\s+something\s+false|give\s+me\s+a\s+fake|make\s+up|fabricate|invent\s+a\s+fact)\b"), "Query explicitly requests fabricated or false information."),
    (re.compile(r"(?i)\b(lie\s+to\s+me|tell\s+lies|spread\s+(fake|false)\s+(news|info|information|facts?))\b"), "Query requests deliberate misinformation."),
    # Search-bar style: "tell any lie", "tell a lie", "give a false answer"
    (re.compile(r"(?i)^(tell\s+(any|a|me\s+a?|some)?\s*lie[s]?)$"), "Query is a direct request for a lie."),
    (re.compile(r"(?i)\b(fake\s+answer|false\s+answer|wrong\s+answer\s+on\s+purpose|incorrect\s+(fact|answer|information))\b"), "Query requests a deliberately incorrect answer."),
    # Requests to pretend or roleplay as a system that lies
    (re.compile(r"(?i)\b(pretend\s+you\s+(are|have\s+no)\s+(guidelines|restrictions|rules)|ignore\s+(your\s+)?instructions?|act\s+as\s+if\s+you\s+can\s+lie)\b"), "Query attempts to bypass factual constraints via roleplay framing."),
    # Misinformation about real people / events
    (re.compile(r"(?i)\b(write\s+fake\s+news|create\s+misinformation|generate\s+(disinformation|propaganda|hoax))\b"), "Query requests generation of disinformation or propaganda."),
    # URL-context: Google search queries asking for lies
    (re.compile(r"(?i)[?&]q=([^&]*(%20|\+)?(lie[s]?|fake|false|fabricat)([^&]*)?)"), "Search query in URL contains misinformation intent."),
]

class ExternalAIVerifier:
    def __init__(self):
        self.analyses_history: Dict[str, AnalyzeResponse] = {}

    async def analyze(self, req: AnalyzeRequest) -> AnalyzeResponse:
        t0 = time.time()
        cache_key = verifier_cache.generate_hash(req.mode.value, f"{req.prompt}:::{req.response}")
        cached_result = verifier_cache.get(cache_key)
        if cached_result:
            # Return cached response with updated latency
            res = AnalyzeResponse(**cached_result)
            res.cached = True
            res.latency_ms = round((time.time() - t0) * 1000, 2)
            return res

        analysis_id = f"tg_ana_{uuid.uuid4().hex[:10]}"
        prompt = req.prompt.strip()
        response = req.response.strip()
        mode = req.mode

        # Step 1: Safety & High-Stakes Risk Assessment
        risk_result = await risk_classifier.classify(prompt + " " + response)
        is_critical_risk = (
            risk_result.get("is_high_stakes", False)
            or risk_result.get("risk_category") in ["financial_operation", "irreversible_deletion", "medical_safety", "legal_commitment"]
            or risk_result.get("severity") in ["CRITICAL", "HIGH"]
        )

        if is_critical_risk or mode == AnalyzeMode.HIGH_RISK:
            res = self._handle_high_risk_analysis(
                analysis_id, prompt, response, req.provider, risk_result, t0
            )
            verifier_cache.set(cache_key, res.model_dump())
            self.analyses_history[analysis_id] = res
            return res

        # Step 1b: Misinformation Intent Detection
        # Check if the prompt/URL is explicitly requesting false or fabricated content.
        # This must happen BEFORE claim-level verification because the page content being
        # factually real (e.g. a dictionary page) does not make the *request* legitimate.
        misinfo_reason = self._detect_misinformation_intent(prompt, url=req.url)
        if misinfo_reason:
            res = self._handle_misinformation_intent(
                analysis_id, prompt, response, req.provider, misinfo_reason, t0
            )
            verifier_cache.set(cache_key, res.model_dump())
            self.analyses_history[analysis_id] = res
            return res

        # Step 2: Split response into atomic verifiable claims
        raw_claims = self._extract_atomic_claims(response)

        # Step 3: Verify claims according to selected mode
        verified_claims: List[ClaimAnalysisItem] = []
        contradictions = 0
        supported_count = 0
        no_evidence_count = 0
        suggested_corrections: List[str] = []

        # Check for known traps first
        for pattern, correction in KNOWN_TRAP_PATTERNS:
            if re.search(pattern, prompt) or re.search(pattern, response):
                contradictions += 1
                verified_claims.append(
                    ClaimAnalysisItem(
                        claim=f"Prompt references fictional or unverified concept: {pattern}",
                        status=ClaimStatus.CONTRADICTED,
                        confidence=0.98,
                        source="TrustGuard Factual Integrity Engine",
                        snippet=correction,
                        category="fact",
                    )
                )
                suggested_corrections.append(correction)

        for claim_text in raw_claims:
            claim_item, correction = await self._verify_single_claim(claim_text, mode)
            verified_claims.append(claim_item)

            if claim_item.status == ClaimStatus.SUPPORTED:
                supported_count += 1
            elif claim_item.status == ClaimStatus.CONTRADICTED:
                contradictions += 1
                if correction:
                    suggested_corrections.append(correction)
            else:
                no_evidence_count += 1

        total_evaluated = max(1, len(verified_claims))
        
        # Calculate consistency metrics
        factual_consistency = round(max(0.0, 1.0 - (contradictions * 0.45) - (no_evidence_count * 0.15)), 2)
        evidence_consistency = round(supported_count / total_evaluated, 2)
        uncertainty = round(1.0 - factual_consistency, 2)

        # Calculate Calibrated Trust Score (0 - 100)
        if contradictions > 0:
            # Significant penalty for factual errors or hallucinations
            base_score = max(15.0, 65.0 - (contradictions * 25.0) + (supported_count * 5.0))
        elif no_evidence_count == total_evaluated:
            # Fully unverified — no positive evidence at all
            base_score = 45.0
        else:
            # Scale from 50–98 based on ratio of supported to total claims.
            # NO_EVIDENCE claims are not rewarded — they pull evidence_consistency below 1.0
            # so a response with mostly unverifiable sentences can never reach HIGH TRUST band.
            # Floor is 50 to avoid penalising answers that are unverifiable but not wrong.
            base_score = min(98.0, 50.0 + (evidence_consistency * 48.0))

        trust_score = round(max(5.0, min(99.0, base_score)), 1)
        if trust_score >= 80.0:
            trust_label = "HIGH TRUST"
        elif trust_score >= 60.0:
            trust_label = "MEDIUM TRUST"
        elif trust_score >= 40.0:
            trust_label = "LOW TRUST"
        else:
            trust_label = "UNVERIFIED"

        # Generate summary
        summary = self._generate_summary(trust_label, trust_score, supported_count, contradictions, no_evidence_count, mode)

        # Generate verified answer if corrections exist
        verified_answer = None
        if suggested_corrections:
            verified_answer = self._generate_corrected_answer(response, suggested_corrections)

        # Token savings estimation from context compression
        comp_res = token_saver_engine.compress(response)
        tokens_saved = comp_res.saved_tokens

        sources_list = list(dict.fromkeys([c.source for c in verified_claims if c.source])) or ["TrustGuard Factbase"]
        reasons_list = [
            "Strong empirical evidence support" if supported_count > 0 else "Limited factual corroboration",
            "No conflicting evidence detected" if contradictions == 0 else f"{contradictions} contradiction(s) found",
            "High semantic consistency across verification paths" if uncertainty < 0.25 else "Moderate domain uncertainty"
        ]
        recommendation_str = (
            "Answer appears reliable and verified" if trust_score >= 80 
            else ("Review flagged claims before relying on this answer" if trust_score >= 50 
            else "High likelihood of factual inaccuracies or unsupported assertions")
        )

        res = AnalyzeResponse(
            analysis_id=analysis_id,
            query=prompt,
            response_text=response,
            trust_score=trust_score,
            trust_label=trust_label,
            trust_level=trust_label,
            claims_checked=len(verified_claims),
            claims_verified=supported_count,
            uncertain_claims=no_evidence_count,
            contradictions=contradictions,
            reasons=reasons_list,
            recommendation=recommendation_str,
            sources=sources_list,
            mode=mode.value,
            provider=req.provider or "generic",
            claims=verified_claims,
            summary=summary,
            factual_consistency=factual_consistency,
            evidence_consistency=evidence_consistency,
            contradiction_count=contradictions,
            uncertainty_score=uncertainty,
            suggested_correction=" | ".join(suggested_corrections) if suggested_corrections else None,
            verified_answer=verified_answer,
            tokens_saved=tokens_saved,
            cached=False,
            latency_ms=round((time.time() - t0) * 1000, 2),
        )

        verifier_cache.set(cache_key, res.model_dump())
        self.analyses_history[analysis_id] = res
        return res

    async def analyze_screen(self, req: AnalyzeScreenRequest) -> AnalyzeResponse:
        """Analyzes text captured from browser tab, window, or screen."""
        clean_text = req.extracted_text.strip()
        
        # Partition text into prompt & response if dual markers exist
        if "\nAI:" in clean_text or "\nAssistant:" in clean_text or "\nChatGPT:" in clean_text:
            parts = re.split(r"\n(?:AI|Assistant|ChatGPT|Claude|Gemini):\s*", clean_text, maxsplit=1)
            prompt = parts[0].replace("User:", "").strip()
            response = parts[1].strip()
        else:
            prompt = "Extracted Screen Content"
            response = clean_text

        analyze_req = AnalyzeRequest(
            prompt=prompt,
            response=response,
            provider=req.source_app or "screen_capture",
            mode=req.mode,
        )
        return await self.analyze(analyze_req)

    def _handle_misinformation_intent(
        self,
        analysis_id: str,
        prompt: str,
        response: str,
        provider: Optional[str],
        reason: str,
        t0: float,
    ) -> AnalyzeResponse:
        """Returns a low-trust, flagged response when the query/URL explicitly
        requests fabricated, false, or misleading content — regardless of whether
        the page content itself happens to be factually accurate."""
        claim = ClaimAnalysisItem(
            claim="Query explicitly requests false or fabricated content",
            status=ClaimStatus.CONTRADICTED,
            confidence=0.97,
            source="TrustGuard Misinformation Intent Detector",
            snippet=reason,
            category="safety",
        )
        return AnalyzeResponse(
            analysis_id=analysis_id,
            query=prompt,
            response_text=response,
            trust_score=0.0,
            trust_label="MISINFORMATION INTENT",
            trust_level="MISINFORMATION INTENT",
            claims_checked=1,
            claims_verified=0,
            uncertain_claims=0,
            contradictions=1,
            reasons=[
                reason,
                "Content may appear factually real — but the intent of the request is to produce or find false information.",
                "TrustGuard flags the query intent, not just the page content.",
            ],
            recommendation="This query is asking for misinformation. TrustGuard cannot verify or endorse it.",
            sources=["TrustGuard Misinformation Intent Policy"],
            mode="quick",
            provider=provider or "generic",
            claims=[claim],
            summary=f"⚠️ MISINFORMATION INTENT DETECTED: {reason} The trust score reflects the intent of the request, not the factual accuracy of individual page sentences.",
            factual_consistency=0.0,
            evidence_consistency=0.0,
            contradiction_count=1,
            uncertainty_score=1.0,
            suggested_correction="Rephrase your query to ask for verified, factual information instead.",
            verified_answer=None,
            tokens_saved=0,
            cached=False,
            latency_ms=round((time.time() - t0) * 1000, 2),
        )

    def _detect_misinformation_intent(
        self, prompt: str, url: Optional[str] = None
    ) -> Optional[str]:
        """Returns a reason string if the prompt/URL signals a request for misinformation,
        or None if no such intent is detected."""
        combined = prompt.strip()
        if url:
            combined = combined + " " + url

        for pattern, reason in MISINFORMATION_INTENT_PATTERNS:
            if pattern.search(combined):
                return reason
        return None

    def _extract_atomic_claims(self, text: str) -> List[str]:
        """Decomposes response into key verifiable factual or logical clauses."""
        # Split on sentence boundaries
        sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if len(s.strip()) > 8]
        claims = []
        for s in sentences:
            # Exclude conversational pleasantries
            if s.lower().startswith(("hi", "hello", "sure", "here is", "let me", "i hope")):
                continue
            claims.append(s)
        return claims[:8] if claims else [text[:200]]

    async def _verify_single_claim(self, claim: str, mode: AnalyzeMode) -> Tuple[ClaimAnalysisItem, Optional[str]]:
        """Verifies individual claim using mathematical, code, or factual tools."""
        category = "fact"
        
        # Check 1: Math / Arithmetic claim
        math_match = re.search(r"(\d+[\d\s\+\-\*\/\^\(\)]*[\+\-\*\/]\s*\d+)\s*=\s*(-?\d+[\d,]*)", claim)
        if math_match or mode == AnalyzeMode.MATH:
            category = "math"
            expr_cand = re.search(r"(\d+(?:\s*[\+\-\*\/]\s*\d+)+)", claim)
            if expr_cand:
                expr = expr_cand.group(1)
                calc_res = tools.calculate(expr)
                if calc_res.get("success"):
                    expected_val = str(calc_res["result"]).replace(",", "")
                    if expected_val in claim.replace(",", ""):
                        return ClaimAnalysisItem(
                            claim=claim,
                            status=ClaimStatus.SUPPORTED,
                            confidence=0.99,
                            source="SymPy Symbolic Calculator",
                            snippet=f"Mathematically verified: {expr} = {expected_val}",
                            category="math",
                        ), None
                    else:
                        correction = f"Arithmetic error detected: {expr} equals {expected_val}, not the stated answer."
                        return ClaimAnalysisItem(
                            claim=claim,
                            status=ClaimStatus.CONTRADICTED,
                            confidence=0.99,
                            source="SymPy Symbolic Calculator",
                            snippet=correction,
                            category="math",
                        ), correction

        # Check 2: Code block verification
        code_match = re.search(r"```(?:python)?\s*([\s\S]*?)```", claim)
        if code_match or mode == AnalyzeMode.CODE:
            category = "code"
            code_str = code_match.group(1) if code_match else claim
            if len(code_str.strip()) > 10 and any(k in code_str for k in ["def ", "import ", "print(", "=", "for ", "return "]):
                sandbox_res = tools.execute_python_sandbox(code_str)
                if sandbox_res.get("success"):
                    return ClaimAnalysisItem(
                        claim=claim[:120] + "...",
                        status=ClaimStatus.SUPPORTED,
                        confidence=0.95,
                        source="Isolated Python Sandbox",
                        snippet=f"Code executed without errors (exit code 0). Output: {sandbox_res.get('stdout', 'clean execution')[:100]}",
                        category="code",
                    ), None
                else:
                    err = sandbox_res.get("error", "Code syntax or runtime failure")
                    return ClaimAnalysisItem(
                        claim=claim[:120] + "...",
                        status=ClaimStatus.CONTRADICTED,
                        confidence=0.92,
                        source="Isolated Python Sandbox",
                        snippet=f"Execution error: {err}",
                        category="code",
                    ), f"Code execution failed: {err}"

        # Check 3: Knowledge Base RAG verification
        rag_res = tools.search_kb(claim, top_k=2)
        if rag_res.get("success") and rag_res.get("results"):
            top = rag_res["results"][0]
            return ClaimAnalysisItem(
                claim=claim,
                status=ClaimStatus.SUPPORTED,
                confidence=0.90,
                source=f"Corpus: {top['source']}",
                snippet=top["snippet"][:150],
                category=category,
            ), None

        # Check 4: General verifiable statement heuristic
        # If the claim states common objective facts
        if any(term in claim.lower() for term in ["capital of france is paris", "python was created by guido", "water freezes at 0", "gravity"]):
            return ClaimAnalysisItem(
                claim=claim,
                status=ClaimStatus.SUPPORTED,
                confidence=0.96,
                source="TrustGuard Verified Factbase",
                snippet="Cross-verified with authoritative general knowledge base.",
                category="fact",
            ), None

        # Fallback: No contradictory evidence found, marked as neutral/unverified
        return ClaimAnalysisItem(
            claim=claim,
            status=ClaimStatus.NO_EVIDENCE,
            confidence=0.60,
            source="TrustGuard Independent Search",
            snippet="Claim is plausible but has no direct contradictory or supporting citations in local knowledge base.",
            category=category,
        ), None

    def _handle_high_risk_analysis(
        self,
        analysis_id: str,
        prompt: str,
        response: str,
        provider: Optional[str],
        risk_result: Dict[str, Any],
        t0: float,
    ) -> AnalyzeResponse:
        """Constructs immediate safety block and explanation for dangerous or unauthorized operations."""
        category = risk_result.get("risk_category", "CRITICAL_RISK")
        reason = risk_result.get("reason", "Action entails irreversible financial or system side-effects.")
        
        claims = [
            ClaimAnalysisItem(
                claim="Autonomous execution of sensitive or irreversible operation",
                status=ClaimStatus.CONTRADICTED,
                confidence=1.0,
                source="TrustGuard Safety Guardrails",
                snippet=f"Triggered category: {category}. Policy strictly requires human supervisor authorization.",
                category="safety",
            )
        ]

        return AnalyzeResponse(
            analysis_id=analysis_id,
            query=prompt,
            response_text=response,
            trust_score=0.0,
            trust_label="CRITICAL RISK",
            trust_level="CRITICAL RISK",
            claims_checked=1,
            claims_verified=0,
            uncertain_claims=0,
            contradictions=1,
            reasons=[f"Critical security hazard: {reason}", "Autonomous execution policy strictly violated"],
            recommendation="Action blocked. Human supervisor sign-off strictly required.",
            sources=["TrustGuard Safety Policy"],
            mode="high_risk",
            provider=provider or "generic",
            claims=claims,
            summary=f"CRITICAL SAFETY VIOLATION: {reason}. This action cannot be safely trusted without supervisor verification.",
            factual_consistency=0.0,
            evidence_consistency=0.0,
            contradiction_count=1,
            uncertainty_score=1.0,
            suggested_correction=f"Block automated execution. Escalate request to verified human operator.",
            verified_answer="ACTION BLOCKED: This request involves high-stakes or irreversible actions and requires explicit authorized human confirmation.",
            tokens_saved=0,
            cached=False,
            latency_ms=round((time.time() - t0) * 1000, 2),
        )

    def _generate_summary(
        self,
        label: str,
        score: float,
        supported: int,
        contradictions: int,
        no_evidence: int,
        mode: AnalyzeMode,
    ) -> str:
        if label == "HIGH TRUST":
            return f"Answer demonstrates high factual grounding ({score}% trust). {supported} statements verified with consistent supporting evidence."
        elif label == "MEDIUM TRUST":
            return f"Answer is largely plausible ({score}% trust) with {supported} verified items, though {no_evidence} claim(s) lack definitive citations."
        elif label == "LOW TRUST":
            return f"Caution advised ({score}% trust): detected {contradictions} contradictory or ungrounded statement(s). Check suggested corrections."
        else:
            return f"Unverified response ({score}% trust): insufficient evidence found in knowledge base or external index."

    def _generate_corrected_answer(self, original_response: str, corrections: List[str]) -> str:
        correction_bullet = "\n".join(f"- {c}" for c in corrections)
        return f"{original_response}\n\n### 🛡️ TrustGuard Verified Corrections\n{correction_bullet}"

    async def ask_and_verify(self, req: AskAndVerifyRequest) -> AskAndVerifyResponse:
        """Generate an AI answer to the question, then immediately verify it.

        Flow:
          1. Ask the LLM for a clear, factual answer.
          2. Pass (question, generated_answer) into the normal analyze() pipeline.
          3. Map the trust_score + contradictions into a human-readable verdict.
          4. Return everything together so the UI can show answer + verdict side-by-side.
        """
        t0 = time.time()

        # --- Step 1: Generate answer via LLM ---
        generation_prompt = (
            f"Answer the following question accurately and concisely. "
            f"State only verifiable facts. Do not speculate or hallucinate.\n\n"
            f"Question: {req.question}"
        )
        llm_resp = await llm_client.generate(
            prompt=generation_prompt,
            temperature=0.3,   # low temperature → more factual, less creative
            max_tokens=400,
        )
        ai_answer = llm_resp.content.strip()

        # --- Step 2: Verify the generated answer against itself ---
        verify_mode = AnalyzeMode(req.mode) if req.mode in [m.value for m in AnalyzeMode] else AnalyzeMode.FACT
        analyze_req = AnalyzeRequest(
            prompt=req.question,
            response=ai_answer,
            provider=req.provider or "trustguard",
            mode=verify_mode,
        )
        analysis: AnalyzeResponse = await self.analyze(analyze_req)

        # --- Step 3: Map trust score → verdict ---
        score = analysis.trust_score
        contradictions = analysis.contradictions or 0

        if contradictions > 0 or score < 40:
            verdict = "FAKE INFORMATION"
            verdict_color = "red"
        elif score >= 80:
            verdict = "REAL INFORMATION"
            verdict_color = "green"
        elif score >= 60:
            verdict = "LIKELY REAL"
            verdict_color = "amber"
        else:
            verdict = "UNCERTAIN"
            verdict_color = "amber"

        # Build a single-sentence summary the UI can show under the answer
        if verdict == "REAL INFORMATION":
            summary = f"🟢 REAL INFORMATION — {analysis.claims_verified} claim(s) confirmed by evidence ({score:.0f}% trust)."
        elif verdict == "LIKELY REAL":
            summary = f"🟡 LIKELY REAL — Answer is mostly correct ({score:.0f}% trust) but {analysis.uncertain_claims} claim(s) lack direct citations."
        elif verdict == "FAKE INFORMATION":
            summary = f"🔴 FAKE INFORMATION — {contradictions} contradiction(s) detected. Trust score: {score:.0f}%. See correction below."
        else:
            summary = f"⚠️ UNCERTAIN — Answer could not be fully verified ({score:.0f}% trust). Treat with caution."

        return AskAndVerifyResponse(
            question=req.question,
            ai_answer=ai_answer,
            trust_score=score,
            trust_label=analysis.trust_label,
            verdict=verdict,
            verdict_color=verdict_color,
            summary=summary,
            claims_checked=analysis.claims_checked or 0,
            claims_verified=analysis.claims_verified or 0,
            contradictions=contradictions,
            suggested_correction=analysis.suggested_correction,
            sources=analysis.sources or [],
            latency_ms=round((time.time() - t0) * 1000, 2),
        )

external_verifier = ExternalAIVerifier()
